services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./tests:/app/tests
      - ./data/animals-10:/app/data/animals-10
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G


  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./templates:/app/templates
    environment:
      - PYTHONPATH=/app
    command: [ "pytest", "-v", "--cov=app", "--cov-report=html" ]


  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  qdrant_data:
  ollama_data: